### ISSUE TITLE
Window too big lmao

### ISSUE THREAD

**Issue by JkHowling** [xCrystal/crystal-randofuser#3]
Downloaded this in hopes of trying out a new locke. Downloaded the zip, unzipped it, opened the jar file- and curiously enough, the window stretched off my screen? Meaning I can't click or even see the "Randofuse!" button to actually use the program. 

Can't make the window size smaller. Can't scroll down. Can't move it up high enough. Nothing works :/ Maybe adjust the window size so it's not as long vertically, or add a scroll bar or something, for screens that aren't as big? I thought my laptop screen was standard size but ig it's smaller than I thought. 

![image](https://user-images.githubusercontent.com/26156840/27254573-ad667c9e-533f-11e7-820a-baf95dc55fa2.png)

**Comment by xCrystal** [comment]
Yeah, window height is 800 px. I'll see what I can do

**Comment by xCrystal** [comment]
The window should be your screen height at most and scrollable now. Try redownloading it from the same release and let me know if it works (or just close this issue if it does).

**Comment by JkHowling** [comment]
Works a little better now. It's still awkwardly massive on my screen and drops off the edge of it [left], but I can barely hit the edge of the Randofuse button now. I still think it'd look overall better for a wider variety of people's screens if it was a bit smaller with the added scroll bar- like the size of the randomizer [right], for example- but it's no longer an issue so I'll leave it at that. Thanks a bunch!

![image](https://user-images.githubusercontent.com/26156840/27270550-d1370f82-5473-11e7-9bf9-a22b54d17a5f.png)
